spring:
  profiles:
    active: native
---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations:
            file:///F:/JAGAN/MicroServices/ms-config-properties/{application}/{profile},
            file:///F:/JAGAN/MicroServices/ms-config-properties/global/{profile}
---
spring:
  profiles: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kj-test/microservices/
          search-paths:
          - "ms-config-properties/{application}/{profile}"
          - "ms-config-properties/{global}/{profile}"